### PR TITLE
[WIP] Add QASP content with conflicting headers, styles

### PR DESCRIPTION
**Pull request by beechnut**
Addresses [TLC #360](https://github.com/18F/TLC-crew/issues/360)

### CODE REVIEW

**Comment by beechnut** [comment]
@alexbielen @igorkorenfeld **Is there existing guidance** on what I'm calling "page title conflicts"?

For example, [the QASP page of the de-risking guide](https://derisking-guide.18f.gov/qasp/) has a page title (e.g. H1) of "Sample Quality Assessment Surveillance Plan (QASP)" but the page tab title is "QASP | De-risking government technology | 18F". And in the replatformed guides, the site title is appended, so we'd get something like "Sample Quality Assessment Surveillance Plan (QASP) | 18F Approaches", which doesn't seem right either.

**Comment by igorkorenfeld** [comment]
The way I've been dealing with is changing the title in the frontmatter to just the page title (without the vertical separator or anything that comes after it). I think we likely ought to update the page template so that the title appends the guide name, either in place of or in addition to the "18F approaches".  So for this guide it would be "Sample Quality Assessment Surveillance Plan (QASP) | De-risking guide".  That's my suggestion but we could consult a content strategist here too?

**Comment by beechnut** [comment]
Thanks, I do like that approach — and perhaps with an " | 18F" at the end too for good measure.

I guess the natural follow-up question is, should we open that guides title decision and work as a separate issue?

**Comment by igorkorenfeld** [comment]
Sounds good to me!

**Pull request closed without merging**
