### PR TITLE
Clarify who reviews content changes.

### PR DESCRIPTION
**Pull request by adunkman**
A challenge which we need to solve when consolidating our Guides & Methods is clearly communicating who is responsible for reviewing and approving pull requests, so that the content remains useful and updated. This PR takes a step in that direction. I expect we will need to revisit this plan shortly. 

This is part of the `next` phase of the [Roadmap update in July](https://docs.google.com/presentation/d/1BRkxeic_39_oK-zQYmbfXpCrJuR_MZaZnFmnQS7WSoE/edit#slide=id.g5ecdbbee9e_0_0) — and following up on recommendations made in [#374](https://github.com/18F/TLC-crew/issues/374).

I reached out to those below, to set these expectations: 

> **What I’m asking of you**
>As a part of the broader effort, and in efforts to maintain and update content, the TLC crew will be proposing changes to the combined guides. Some of those changes will be revising content that subject matter experts should be reviewing, and I’m asking you to be one of those subject matter experts.
>
>Today, that will closely mimic the structure of our previous guides & methods. As we adapt to what is learned through researching a unified information architecture, we’ll need to adapt how we involve subject matter experts so it is clear who will review and approve changes. 
>
>If you say yes, I’ll mark you to automatically be tagged for reviewing GitHub pull requests for content changes.
>
> **What to consider when reviewing**
>I’m asking you to consider that the guides are specific to 18F and its practices — that is, the ones we actively use and recommend on our projects. If you have questions or concerns, feel free to tag me (or others) in for review — you needn’t be the only authority on this, but because of your expertise you are likely a good candidate for review, and would know who else to involve if needed. 
>
>I ask you to opt for action over inaction, and to ask for help when needed. If you are comfortable with the change, you are the authority — you can merge as you deem appropriate. I’ve already spoken with the other members of the 18F leadership team, and they are supportive of you in this role. 

## Changes proposed in this pull request:

- Establishes a CODEOWNERS file to auto-tag pull request reviewers
- Adds a note to the README to point people to CODEOWNERS

## Security considerations

No new considerations — changes are to documentation and GitHub process flow. Security considerations relate to these contributor’s push access to this repository, which is an existing consideration and has internal controls associated with it.

### CODE REVIEW

**Review by MelissaBraxton — APPROVED** [review]
Looks good to me! 

One optional suggestion - including some expectation of what we mean by "timely" review could stave off resentment stemming from misaligned expectations on how quickly PRs are approved. Given that this has historically been a volunteer role I think there's a legacy of guides/methods PRs not seen as needing urgent attention (which means improvements sometimes languished). Now is a chance to establish a different expectation--if you have one! :)

**Comment by alexbielen** [comment]
@adunkman it looks good to me. One quick clarification that may result in request: does the Code Owner for a specific directory supersede the TLC Crew? For example, if @eric-gade or I would like to update a link on the Agile guide, would that go to you for review?

**Comment by adunkman** [comment]
> … some expectation of what we mean by "timely" review could stave off resentment… Now is a chance to establish a different expectation--if you have one! :)

Great idea @MelissaBraxton! I’ll set this at 2 weeks, as it’s a volunteer role, and we can see how that works. (If others reading this have opinions, please reach out!). Update incoming. 

> does the Code Owner for a specific directory supersede the TLC Crew?

@alexbielen Yes, the rules supersede each other down the file. I limited these to Markdown files to try to target content-only, so thinks like dependency updates and template changes don’t trigger SME review and fallback to the TLC Crew.

**Comment by alexbielen** [comment]
@adunkman thanks! In that case, I would like to find a way for TLC Crew to have code owner-level of access in the interim while we are actively replatforming. There are a number of URLs in the content that need updated, and I think the coordination headwind would add a lot of complication at this point. Once we've replatformed, we can remove that access. Thoughts?

**Comment by adunkman** [comment]
> I would like to find a way for TLC Crew to have code owner-level of access in the interim while we are actively replatforming.

@alexbielen I agree. I’ll merge this with Melissa’s 👍 above, and for now, we’ll use this judgement for you and TLC members:

We don’t currently have branch protection rules enabled, (I think) you should be able to still review and merge pull requests. If that isn’t the case, we can make changes. 

- Please use your judgement here and approve PRs which are replatform-related even when they request review from content SMEs, as long as they don’t touch significant content changes. 
- Please use those SME reviewers for those significant content changes.

**Comment by igorkorenfeld** [comment]
@adunkman, @alexbielen, @juliaklindpaintner 

Because most of the work that we are currently doing on the guides is focused on the re-platforming, rather than content changes, I'm finding that we untag the auto-tagged reviewers on nearly every PR. There doesn't seem to be a way to do that before the PR is opened. I am conscious of the unnecessary notification the PRs generate for the guide authors, and I just learned that the owners don't get notified they are untagged which can create some unnecessary work. One suggestion I have for this phase of work is commenting out the codeowner in the file until the guide is released, and adding uncommenting the codeowner to the launch checklist. We could leave the TLC-crew as the default auto-tagged team. What do you all think?

**Comment by adunkman** [comment]
That makes sense to me!

**Pull request merged**
