### PR TITLE
Add content guide

### PR DESCRIPTION
**Pull request by igorkorenfeld**
## Changes proposed in this pull request:
This PR adds the content-guide pages to the approaches. In order to match the current content guide this PR also adds in:
- "Subnav" options to include anchor links on the page in the sidebar
- Fixes to the current page logic in the navigation 
- Updates to the documentation on sidenavs
- Minor typographic style adjustments

👓  [Preview](https://federalist-864a0936-e148-4df8-8602-6b0992887566.sites.pages.cloud.gov/preview/18f/approaches/ik/289-content-guide/)

### CODE REVIEW

**Comment by michelle-rago** [comment]
Review checklist developed by @geekygirlsarah.

[ ] Make sure there's some icon on the home page that links to the guide
[ ] visit every page in the main navigation and sidebar navigation to make sure they load
[ ] Click at least a couple of links within the guide pages to make sure they navigate to the correct guide page
[ ] The title on every page should be the 18F logo and the name of the guide
[ ] Check that all images on the production guides match the same images on the new guides
[ ] Look for any stray { ... } or {{ ... }} type curly brace tags. They shouldn't be visible on these pages.
[ ] Make sure the appropriate navigation shows up on every page (and not a test menu)
[ ] Make sure the navigation menus on new and old guides have all the same links
[ ] Internal/private links (like Google Docs) should have a lock icon and Slack channel links should have a Slack icon
[ ] Page aesthetics should be about the same across all pages. (like one page isn't wider than others, different font sizes, etc.)
[ ] The main USWDS-type theme should be on each page. (18F icon, search bar, "An official website of the US gov", GSA footer, etc.)

**Comment by michelle-rago** [comment]
@igorkorenfeld I added my review. Let me know if something doesn't make sense or if you have suggestions for the format.

**Comment by igorkorenfeld** [comment]
@michelle-rago this was great, thank you for the through review! I think addressed all of them, let me know if I missed anything.

**Comment by michelle-rago** [comment]
@igorkorenfeld Looks great! I made the title title case, after conferring with @durland18F. I also added the "URL redirect" text back in but just removed the link.

**Review by loganmeetsworld — APPROVED** [review]
Approving on the technical side - everything looks good to me!

**Pull request merged**
